# This file contains the fastlane.tools configuration
# for the iOS half of the Skip app.
# You can find the documentation at https://docs.fastlane.tools

default_platform(:ios)

before_all do
  setup_ci if ENV["CI"]
end

lane :assemble do |options|
  # only build the iOS side of the app
  ENV["SKIP_ZERO"] = "true"
  build_app(
    scheme: "Kourt App",
    sdk: "iphoneos",
    xcconfig: "fastlane/AppStore.xcconfig",
    xcargs: "-skipPackagePluginValidation -skipMacroValidation",
    derived_data_path: "../.build/Darwin/DerivedData",
    output_directory: "../.build/fastlane/Darwin",
    skip_archive: ENV["FASTLANE_SKIP_ARCHIVE"] == "YES",
    skip_codesigning: ENV["FASTLANE_SKIP_CODESIGNING"] == "YES"
  )
end

lane :setup_signing do |options|
  api_key = lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]
  team_id = CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
  app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)

  if team_id.nil?
    UI.user_error!("Team ID is not defined in the Appfile. Please add it there or configure it dynamically.")
  end

  if app_identifier.nil?
    UI.user_error!("App Identifier is not defined in the Appfile. Please add it there or configure it dynamically.")
  end

  app_store_connect_api_key(
    key_id: ENV["ASC_KEY_ID"],
    issuer_id: ENV["ASC_ISSUER_ID"],
    key_content: ENV["ASC_KEY_CONTENT"],
    is_key_content_base64: true,
    in_house: false
  )

  # configure code signing settings
  sync_code_signing(
    type: "appstore",
    app_identifier: [app_identifier, "#{app_identifier}.KourtWidget"],
    readonly: is_ci
  )
  update_code_signing_settings(
    use_automatic_signing: false,
    team_id: team_id,
    targets: ["Kourt App"],
    profile_name: lane_context[:MATCH_PROVISIONING_PROFILE_MAPPING][app_identifier],
    code_sign_identity: "Apple Distribution"
  )
  update_code_signing_settings(
    use_automatic_signing: false,
    team_id: team_id,
    targets: ["KourtWidgetExtension"],
    profile_name: lane_context[:MATCH_PROVISIONING_PROFILE_MAPPING]["#{app_identifier}.KourtWidget"],
    code_sign_identity: "Apple Distribution"
  )
end

lane :bump_build_number do |options|
  next_build_number = latest_testflight_build_number(initial_build_number: 0) + 1

  Dir.chdir("../..") do
    sh("sed -i '' \"s;CURRENT_PROJECT_VERSION = .*;CURRENT_PROJECT_VERSION = #{next_build_number};g\" Skip.env")
  end
end

lane :beta do |options|
  setup_signing
  bump_build_number

  changelog = nil
  Dir.chdir("../..") do
    changelog = sh("./scripts/changelog.sh")
  end

  assemble

  upload_to_testflight(
    api_key: lane_context[SharedValues::APP_STORE_CONNECT_API_KEY],
    distribute_external: true,
    groups: ["External"],
    changelog: changelog
  )
end

lane :release do |options|
  desc "Build and release app"

  # see https://docs.fastlane.tools/uploading-app-privacy-details/
  #upload_app_privacy_details_to_app_store(json_path: "fastlane/app_privacy_details.json")

  setup_signing
  bump_build_number

  changelog = nil
  Dir.chdir("../..") do
    changelog = sh("./scripts/changelog.sh")
  end

  assemble

  upload_to_app_store(
    api_key: lane_context[SharedValues::APP_STORE_CONNECT_API_KEY],
    app_rating_config_path: "fastlane/metadata/rating.json",
    release_notes: { default: changelog }
  )
end

