# This file contains the fastlane.tools configuration
# for the Android half of the Skip app.
# You can find the documentation at https://docs.fastlane.tools

# Load the shared Skip.env properties with the app info
require('dotenv')
Dotenv.load '../../Skip.env'

default_platform(:android)

# use the Homebrew gradle rather than expecting a local gradlew
gradle_bin = (ENV['HOMEBREW_PREFIX'] ? ENV['HOMEBREW_PREFIX'] : "/opt/homebrew") + "/bin/gradle"

before_all do
  setup_ci if ENV["CI"]
end

desc "Build Skip Android App"
lane :build do |options|
  build_config = (options[:release] ? "Release" : "Debug")
  gradle(
    task: "build${build_config}",
    gradle_path: gradle_bin,
    flags: "--warning-mode none -x lint"
  )
end

lane :bump_build_number do |options|
  next_build_number = google_play_track_version_codes(track: options[:track])[0] + 1

  Dir.chdir("../..") do
    sh("sed -i '' \"s;CURRENT_PROJECT_VERSION = .*;CURRENT_PROJECT_VERSION = #{next_build_number};g\" Skip.env")
  end
end

desc "Test Skip Android App"
lane :test do
  gradle(
    task: "test",
    gradle_path: gradle_bin
  )
end

desc "Assemble Skip Android App"
lane :assemble do
  gradle(
    gradle_path: gradle_bin,
    task: "bundleRelease",
    print_command: false,
    properties: {
      "android.injected.signing.store.file" => ENV["ANDROID_SIGN_KEYSTORE_FILE"],
      "android.injected.signing.store.password" => ENV["ANDROID_SIGN_KEYSTORE_PASSWORD"],
      "android.injected.signing.key.alias" => ENV["ANDROID_SIGN_KEY_ALIAS"],
      "android.injected.signing.key.password" => ENV["ANDROID_SIGN_KEY_PASSWORD"]
    }
  )
  # sh "your_script.sh"
end

desc "Deploy Skip Android App to Google Play"
lane :release do
  track = "internal"

  bump_build_number(track: track)

  assemble

  upload_to_play_store(
    track: track,
    release_status: "completed",
    aab: '../.build/Android/app/outputs/bundle/release/app-release.aab'
  )
end
