on:
  push:
    tags:
      - "v*"

jobs:
  ios:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/ios.yml
    secrets: inherit
    with:
      track: beta

  android:
    uses: ./.github/workflows/android.yml
    secrets: inherit
    with:
      track: beta
